---
- name: Configure Nginx Reverse Proxy
  hosts: nginx
  become: true
  vars:
    fe_upstream_host: "10.0.11.136"
  tasks:
    - name: Install nginx
      ansible.builtin.dnf:
        name: nginx
        state: present

    - name: Deploy nginx config
      ansible.builtin.copy:
        dest: /etc/nginx/conf.d/default.conf
        mode: "0644"
        content: |
          server {
            listen 80;
            server_name _;

            location / {
              proxy_pass http://{{ fe_upstream_host }}:{{ app_port }};
              proxy_http_version 1.1;
              proxy_set_header Host $host;
              proxy_set_header X-Real-IP $remote_addr;
              proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
              proxy_set_header X-Forwarded-Proto $scheme;
            }
          }

    - name: Enable and restart nginx
      ansible.builtin.systemd:
        name: nginx
        enabled: true
        state: restarted
